### ISSUE TITLE
Not able to install using Eclipse kepler

### ISSUE THREAD

**Issue by aabhijit23** [nodj/AutoDeriv#4]
Hi 

 I find this very helpful plugin but I am not able to install this with eclipse Kepler. I am using Windows 7. 

I entered the update site and then it correctly pulled version 1.4.1 release but after the that screen when I press Next button it is not downloading the software/plugin.

Please help;
thanks
Abhijit

**Comment by nodj** [comment]
Hello,

I would say it's not linked with this specific plug-in, but perhaps is a
problematic download from eclipse?
The plugin works on my eclipse Kepler on windows 7 myself (that was the dev
plateform actually =) )

I don't expect to work on AutoDeriv anytime soon, unfortunately...
I hope you will find a workaround.

Sorry not to help you...

nodj

**Comment by aabhijit23** [comment]
Hi Nodj
It is possible to download the jar file for the plugin from some where rather than the update site?
It is very helpful plugin as we have almost 60 projects and every project going to target folder is painfull. please let me know.
thanks
Abhijit

**Comment by nodj** [comment]
Hello,
I don't have any access to github right now. If I remember correctly, there
is one branch on the Autoderiv project which contains all the update site.
In that branch, you can search for the .jars.
Sorry again, not a cool answer. I'm sorry about that. (I don't have much
time for my personnal projects anymore...)

Tell me if you find something cool :)

Johan

**Comment by aabhijit23** [comment]
Cannot complete the install because one or more required items could not be found.
Thanks for help.

I get following error in eclispe - 
 Software being installed: AutoDeriv 1.4.1.201412191942 (net.nodj.AutoDerivFeature.feature.group 1.4.1.201412191942)
  Missing requirement: AutoDeriv 1.4.1.201412191942 (net.nodj.AutoDerivPlugin 1.4.1.201412191942) requires 'bundle org.eclipse.core.resources 3.9.1' but it could not be found
  Cannot satisfy dependency:
    From: AutoDeriv 1.4.1.2014121919

**Comment by nodj** [comment]
I just install the plugin on Luna from "
http://nodj.github.io/AutoDeriv/update", everythings looks OK.
I can't lead additional test for now unfortunately. Did you try with Luna ?
Even if it's not the IDE you will use for work, it might be a good start to
try that.
I guess you've found this page http://nodj.github.io/AutoDeriv/ ?

Johan

**Comment by jpirie** [comment]
Just in case anyone finds this information helpful, this bug is definitely eclipse version specific. I can reproduce this issue using Keplar Service Release 1, however using Mars, I cannot reproduce this issue.

I guess the only solution if using Keplar like me is to dig out the jar from the repository.

**Comment by afboteroz** [comment]
Hi, i have the same problem with Kepler Service Release 2 (Build id: 20140224-0627)

Cannot complete the install because one or more required items could not be found.
  Software being installed: AutoDeriv 1.4.1.201412191942 (net.nodj.AutoDerivFeature.feature.group 1.4.1.201412191942)
  Missing requirement: AutoDeriv 1.4.1.201412191942 (net.nodj.AutoDerivPlugin 1.4.1.201412191942) requires 'bundle org.eclipse.core.resources 3.9.1' but it could not be found
  Cannot satisfy dependency:
    From: AutoDeriv 1.4.1.201412191942 (net.nodj.AutoDerivFeature.feature.group 1.4.1.201412191942)
    To: net.nodj.AutoDerivPlugin [1.4.1.201412191942]

**Comment by nodj** [comment]
Hi, thanks for the report.
I won't be able to analyse/fix this issue anytime soon unfortunately
(moving, so no PC/ no time + lack of expertise about the eclipse platform).

I should tag the issue "Help wanted" cause it's a shame to be blocked by a
simple installation problem.

I'm sincerly sorry to let you down guys :s
Do not hesitate to suggest a bugfix, or even better a pull request, it
would be great !

**Comment by jnuc093** [comment]
Cannot complete the install because one or more required items could not be found.
  Software being installed: AutoDeriv 1.4.1.201412191942 (net.nodj.AutoDerivFeature.feature.group 1.4.1.201412191942)
  Missing requirement: AutoDeriv 1.4.1.201412191942 (net.nodj.AutoDerivPlugin 1.4.1.201412191942) requires 'bundle org.eclipse.core.resources 3.9.1' but it could not be found
  Cannot satisfy dependency:
    From: AutoDeriv 1.4.1.201412191942 (net.nodj.AutoDerivFeature.feature.group 1.4.1.201412191942)
    To: net.nodj.AutoDerivPlugin [1.4.1.201412191942]

**Not able to install using Eclipse kepler**
